Repository Qithub-BOT/mastogetter, pull requests merged in 2020-01, with the labels that each got.

#64 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#79 Resolve: URL 欄をクリックしたら選択状態にして欲しい #76
  js/index.js
Labels: enhancement

#82 chore: CONTRIBUTINGの修正
  CONTRIBUTING.md
Labels: documentation

#81 トゥートの並び順をフリップするボタンを作成
  index.html
  js/common.js
  js/index.js
Labels: enhancement

#86 docs: improve: #74 移管にともなう修正
  README.md
Labels: documentation

#83 ヒントアイコンの導入 #47
  css/style.css
  index.html
Labels: enhancement

#72 feat: toot idの圧縮
  .eslintrc.json
  js/common.js
  js/index.js
  js/p.js
  v2/index.html
  v2/js/common.js
  v2/js/index.js
  v2/js/p.js
  v2/p.html
Labels: enhancement

#106 CONTRIBUTING.md の PR までの流れを修正
  CONTRIBUTING.md
  README.md
Labels: documentation

#111 fix(eslint): prefer-constの導入
  .eslintrc.json
  js/index.js
Labels: documentation

#110 fix: 編集画面で並び替え・削除ができない
  js/index.js
Labels: bug

#109 Resolve: Emoji 対応 #103
  css/style.css
  js/common.js
  js/index.js
Labels: enhancement

#115 feat: input parser
  .circleci/config.yml
  .editorconfig
  .eslintrc.json
  js/common.js
  package-lock.json
  package.json
  test/common.test.js
Labels: enhancement

#117 カード追加時に id が重複しないようにする
  js/class/counter.js
  js/common.js
  js/index.js
Labels: bug

#112 feat: introJSの追加
  .eslintrc.json
  css/style.css
  index.html
  js/index.js
Labels: enhancement

#118 Fetch API を使う
  js/common.js
  js/index.js
  js/p.js
Labels: enhancement
